#!/bin/bash

sudo mkdir /opt/py_batmon
sudo cp py_* /opt/py_batmon/
sudo cp startup /opt/py_batmon/startup
sudo cp py_batmon.svg /usr/share/pixmaps/
sudo cp "Py Batmon.desktop" /usr/share/applications/
